### ISSUE TITLE
Exception when starting ledfx

### ISSUE THREAD

**Issue by WolfgangHusen** [ahodges9/LedFx#113]
Hi folks,

i just installed ledfx on my win10 machine (incl. Anaconda).
When starting ledfx, I am receiving the following message:
`(ledfx) PS C:\Users\wolfg> ledfx --open-ui
Loading configuration file from C:\Users\wolfg\AppData\Roaming\.ledfx
Started webinterface at http://192.168.0.121:8888
Exception in thread sACN sending/sender thread:
Traceback (most recent call last):
  File "c:\users\wolfg\.conda\envs\ledfx\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\wolfg\.conda\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 58, in run
c:\users\wolfg\.conda\envs\ledfx\lib\site-packages\ledfx\effects\gradient.py:94: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  gradient = np.hstack(self._color_ease(len(ease_chunks[i]), *color_pairs[i]) for i in range(n_colors-1))
    [self.send_out(output) for output in list(self._outputs.values())
  File "c:\users\wolfg\.conda\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 58, in <listcomp>
    [self.send_out(output) for output in list(self._outputs.values())
  File "c:\users\wolfg\.conda\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 79, in send_out
    self.send_packet(output._packet, udp_ip)
  File "c:\users\wolfg\.conda\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 95, in send_packet
    self._socket.sendto(MESSAGE, (destination, DEFAULT_PORT))
socket.gaierror: [Errno 11001] getaddrinfo failed`

Any ideas what is going wrong?

Thanks,
Wolfgang

**Comment by shauneccles** [comment]
@WolfgangHusen Please uninstall, uninstall anaconda and give the packaged application a go - https://ledfx.app/download

**Comment by WolfgangHusen** [comment]
Thanks -  I uninstalled Anaconda and had to uninstall Python. After installing the packaged installation - it works.
Many thanks!
