### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by Mas0x** [ahodges9/LedFx#127]
(ledfx-linux) mas0x@Mas0xs-Air ~ % ledfx --open-ui
Loading configuration file from /Users/mas0x/.ledfx
Started webinterface at http://192.168.1.235:8888
Traceback (most recent call last):
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/audio.py", line 142, in _audio_sample_callback
    self._invoke_callbacks()
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/audio.py", line 149, in _invoke_callbacks
    callback()
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/audio.py", line 512, in _audio_data_updated
    self.audio_data_updated(self.audio)
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/energy(Reactive).py", line 50, in audio_data_updated
    self.pixels = self._p_filter.update(p)
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/__init__.py", line 186, in pixels
    pixels = blur_pixels(pixels=pixels, sigma=self._config['blur'])
  File "/Users/mas0x/opt/anaconda3/envs/ledfx-linux/lib/python3.6/site-packages/ledfx/effects/__init__.py", line 49, in blur_pixels
    rgb_array[0] = smooth(rgb_array[0], sigma)
ValueError: could not broadcast input array from shape (12) into shape (15)
Stopping LedFx.

Unable to resolve this issue, I'm using anaconda as per the WiKi... 

(obviously I'm trying to install in my Mac)

**Comment by datadrian** [comment]
Try rounding up the number of pixels in your strip to the next even number
so change 15 to 16....



Adrian Stucker
513.341.LENS

**Comment by Mas0x** [comment]
Hey Adrian,

I get this error on launch... WLED is installed and they are all even numbers, when trying to use command ledfx --open-ui the browser opens and displays the panel to add devices etc.

but the terminal gives said error and ledfx stops??

Mas0x

**Comment by datadrian** [comment]
Try deleting all your configured devices and adding them one by one. So
delete them all, close.ledfx and open again, do you get the error with no
devices?

Adrian Stucker
513.341.LENS

**Comment by Mas0x** [comment]
Unable to gain access to /Users/mas0x/.ledfx?

Kinda new to Macs... 

I believe this **Loading configuration file from /Users/mas0x/.ledfx** is what I need to delete, then it will create a blank config?
