### ISSUE TITLE
Listening device

### ISSUE THREAD

**Issue by JutKip** [ahodges9/LedFx#138]
I'm using ESP8266 and WS2812B led light strips
I made my LedFx work perfectly but it's a bummer that It cant listen to pc sound
but instead, it just listens to my microphone
Is there any way around that? can I make it listen to pc somehow?
btw I'm a complete rookie in all this coding and programming world
If anyone can help it would be gladly appreciated!

**Comment by datadrian** [comment]
Instead of a microphone follow the instructions for a 1/8in input. Output
from your headphone jack to that. Use a y cable to send audio to the esp
and your speakers. Does that help?

Adrian Stucker
513.341.LENS

**Comment by JutKip** [comment]
Thank you for fast reply sir!
I don't have headphone jacks, I have wireless headphones via USB
I'm really sorry but I'm a big rookie...I don't know what do you mean by "1/8 input" and "use a y cable"

**Comment by datadrian** [comment]
How would you hook you music up to speakers? You need a solution for that
to begin with. Just Google the terms you don't understand!

Adrian Stucker
513.341.LENS

**Comment by JutKip** [comment]
With assitance of google i understood you're comment 100%!
Im really sorry...I told you i'm a rookie
Now my question is
What to do if im on usb speakers?

**Comment by datadrian** [comment]
Google usb to 1/8 in output

Adrian Stucker
513.341.LENS

**Comment by JutKip** [comment]
Oh and if i connect my speakers via headphone jack it will show up in ledfx menu?

**Comment by datadrian** [comment]
Ok google "virtual line in "



Adrian Stucker
513.341.LENS

**Comment by JutKip** [comment]
Okay i did
So i can make my usb device appear in my playback devices even without aux cable?
And then i can select pc sound on ledfx settings menu?

**Comment by datadrian** [comment]
Yes

Adrian Stucker
513.341.LENS

**Comment by JutKip** [comment]
Thank you very much for you're time sir
I'l give it a try tomorrow
Will post an update here
Thank you once again!

**Comment by not-matt** [comment]
Exactly right. Set up a virtual line in, then set that as the input device
in LedFx.

Setting up your virtual input will be different depending on your operating
system, have a look and let us know what you end up settling on!

**Comment by JutKip** [comment]
my LedFx won't start for some reason.. I can't test the virtual thingy

**Comment by JutKip** [comment]
`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 100, in async_start
    import webbrowser
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\webbrowser.py", line 531, in <module>
    if shutil.which(browser):
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\shutil.py", line 1157, in which
    if _access_check(name, mode):
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\shutil.py", line 1113, in _access_check
    return (os.path.exists(fn) and os.access(fn, mode)
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 512, in _audio_data_updated
    self.audio_data_updated(self.audio)
  File "c:\users\jbenc\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\pitchSpectrum(Reactive).py", line 35, in audio_data_updated
    midi_value = self.pitch_o(data.audio_sample())[0]
ValueError: can only accept vector of float as input
`

**Comment by Mattallmighty** [comment]
Hey guys,

There is quite a bit of development and documentation work recently. 
Have a look at the readme on: https://github.com/ahodges9/LedFx/tree/dev & https://ledfx.readthedocs.io/en/docs/index.html
Can I ask you to try the LedFx Exe version 0.0.3: https://ledfx.app/download/ - note, only x64 bit environment
I have documented sound options on: https://ledfx.readthedocs.io/en/docs/trouble.html#speaker-sound

Your welcome to join the LedFx community on Discord and we can help you out from there: https://discord.com/invite/wJ755dY
