### ISSUE TITLE
Pyaudio problems, can't launch ledfx

### ISSUE THREAD

**Issue by ramzumo** [ahodges9/LedFx#139]
(ledfx) C:\Users\user\anaconda3\envs\ledfx>ledfx --open-ui
Loading configuration file from C:\Users\user\AppData\Roaming\.ledfx
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\ledfx\lib\runpy.py", line 193, in _run_modu
le_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\ledfx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\anaconda3\envs\ledfx\Scripts\ledfx.exe\__main__.py", line
7, in <module>
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\__main__.py",
 line 88, in main
    ledfx = LedFxCore(config_dir = args.config)
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", lin
e 39, in __init__
    port=self.config.get('port', None))
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\http.py", lin
e 19, in __init__
    self.api = RestApi(ledfx)
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\api\__init__.
py", line 33, in __init__
    super().__init__(ledfx, RestEndpoint, self.PACKAGE_NAME)
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", li
ne 189, in __init__
    self.import_registry(package)
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", li
ne 225, in import_registry
    importlib.import_module(name)
  File "c:\users\user\anaconda3\envs\ledfx\lib\importlib\__init__.py", line 126,
 in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\ledfx\api\audio_dev
ices.py", line 6, in <module>
    import pyaudio
  File "c:\users\user\anaconda3\envs\ledfx\lib\site-packages\pyaudio.py", line 1
16, in <module>
    import _portaudio as pa
ImportError: DLL load failed: The specified module was not found.

**Steps what i did:
conda create -n ledfx python=3.6
conda activate ledfx
conda config --add channels conda-forge
conda install aubio portaudio pywin32
conda install -c anaconda pyaudio
pip install pipwin
pipwin install pyaudio
pip install ledfx
ledfx --open-ui**

Can anybody explain what a problem with it?

**Comment by texdetex** [comment]
Same here. I’m following the instructions but not able to execute

**Comment by datadrian** [comment]
Looks like pyaudio isn't installed correctly

Adrian Stucker
513.341.LENS

**Comment by texdetex** [comment]
Start over on a different pc all good now.

**Comment by Mattallmighty** [comment]
Try running:
`conda install portaudio`

And if that doesn't resolve your issue, follow this: https://stackoverflow.com/a/53087826/14312698
