### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Jimothydoesntknow** [ahodges9/LedFx#153]
Everything runs till I try to open the UI. System is windows 10 64 bit.  Tried new version of Anaconda and tried older archived versions with no results.  I also tried running python 3.7 and 3.6 but still having the same issues. I feel that I am so close and I must be missing a small step.  Any help would be greatly appreciated was hoping to have a small light show for my son this Christmas. Below is the error I am getting.

(ledfx) C:\Users\James JR>ledfx --open-ui
Loading configuration file from C:\Users\James JR\AppData\Roaming\.ledfx
Started webinterface at http://192.168.254.58:8888
[2020-11-09 14:26:56] ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 94, in async_start
    self.effects = Effects(self)
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\__init__.py", line 221, in __init__
    super().__init__(ledfx = ledfx, cls = Effect, package = self.PACKAGE_NAME)
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", line 189, in __init__
    self.import_registry(package)
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\ledfx\utils.py", line 225, in import_registry
    importlib.import_module(name)
  File "c:\programdata\anaconda3\envs\ledfx\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 13, in <module>
    import aubio
  File "c:\programdata\anaconda3\envs\ledfx\lib\site-packages\aubio\__init__.py", line 26, in <module>
    from ._aubio import __version__ as version
ImportError: DLL load failed: The specified module could not be found.
Stopping LedFx.

**Comment by Mattallmighty** [comment]
Hey mate, 
Can I please point you to the readme on: https://github.com/ahodges9/LedFx/tree/dev & https://ledfx.readthedocs.io/en/docs/index.html
Can I ask you to try the LedFx Exe version 0.0.3: https://ledfx.app/download/ 

Your welcome to join the developers on LedFx Discord: https://discord.com/invite/wJ755dY

**Comment by Jimothydoesntknow** [comment]
WOW!!!! I have been trying for 4 days now. Thank you for your help!!!  I can't thank you enough. Cheers
