### ISSUE TITLE
(WinError 10065) An attempt was made to perform a socket operation on an unreachable host

### ISSUE THREAD

**Issue by Rost1116** [ahodges9/LedFx#163]
Microsoft Windows [Version 10.0.18363.1139]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\Users\Rost1116>conda activate ledfx

(ledfx) C:\Users\Rost1116>ledfx --open-ui
Loading configuration file from C:\Users\Rost1116\AppData\Roaming\.ledfx
Started webinterface at http://192.168.0.172:8888
[2020-11-25 06:57:46] ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\aiohttp\web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\aiohttp\web_app.py", line 341, in _handle
    resp = await handler(request)
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\ledfx\api\__init__.py", line 26, in handler
    return await method(**{arg_name: available_args[arg_name] for arg_name in wanted_args})
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\ledfx\api\device_effects.py", line 127, in delete
    del device['effect']
KeyError: 'effect'
Exception in thread sACN sending/sender thread:
Traceback (most recent call last):
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 53, in run
    self.send_uni_discover_packets()
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 91, in send_uni_discover_packets
    self.send_packet(packet=packet, destination="<broadcast>")
  File "c:\users\rost1116\anaconda3\envs\ledfx\lib\site-packages\sacn\sending\output_thread.py", line 95, in send_packet
    self._socket.sendto(MESSAGE, (destination, DEFAULT_PORT))
OSError: [WinError 10065] Сделана попытка выполнить операцию на сокете для недоступного хоста

---------------------------------------------------------------------
did it worked beautifully
and one day I want to turn it on, but here I don't understand a mistake

translate.google.com.ua

**Comment by Rost1116** [comment]
I already completely reinstalled led fx
and removed .ledfx in AppData \ Roaming

**Comment by shauneccles** [comment]
Unless you are developing I suggest grabbing the latest version from https://LedFx.app

**Comment by Rost1116** [comment]
Thank you very much
I didn't know about the official site
more about the program

**Comment by Rost1116** [comment]
which program is convenient
and your version

**Comment by Rost1116** [comment]
> Если вы не разрабатываете я предлагаю захватить последнюю версию из [https://LedFx.апп](https://LedFx.app)

whoa
which one
functional
how many functions
baldezh
