### ISSUE TITLE
Ledfx will not install

### ISSUE THREAD

**Issue by Neilo61** [ahodges9/LedFx#170]
Desperate to get this working, where am I going wrong as I have followed every step of the way for installing ledfx. Much appreciate any advice to get this working. Thank you in anticipation.

(ledfx) C:\Users\Neil>pip install ledfx
Requirement already satisfied: ledfx in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (0.7)
Requirement already satisfied: aubio>=0.4.8 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (0.4.9)
Requirement already satisfied: numpy>=1.13.3 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (1.19.4)
Requirement already satisfied: voluptuous==0.11.1 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (0.11.1)
Requirement already satisfied: pypiwin32>=223 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (223)
Requirement already satisfied: aiohttp-jinja2==1.0.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (1.0.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (5.3.1)
Requirement already satisfied: sacn==1.3 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (1.3)
Requirement already satisfied: pyaudio>=0.2.11 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (0.2.11)
Requirement already satisfied: aiohttp==3.3.2 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (3.3.2)
Requirement already satisfied: requests>=2.22.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (2.25.0)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (4.7.6)
Requirement already satisfied: idna-ssl>=1.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (1.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (20.3.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (1.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (3.0.1)
Requirement already satisfied: aiohttp==3.3.2 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (3.3.2)
Requirement already satisfied: jinja2>=2.7 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp-jinja2==1.0.0->ledfx) (2.11.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from ledfx) (1.19.4)
Requirement already satisfied: idna>=2.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from idna-ssl>=1.0->aiohttp==3.3.2->ledfx) (2.10)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from jinja2>=2.7->aiohttp-jinja2==1.0.0->ledfx) (1.1.1)
Requirement already satisfied: pywin32>=223 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from pypiwin32>=223->ledfx) (228)
Requirement already satisfied: idna>=2.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from idna-ssl>=1.0->aiohttp==3.3.2->ledfx) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from requests>=2.22.0->ledfx) (2020.6.20)
Requirement already satisfied: chardet<4.0,>=2.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from requests>=2.22.0->ledfx) (1.26.2)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from yarl<2.0,>=1.0->aiohttp==3.3.2->ledfx) (3.7.4.3)
Requirement already satisfied: multidict<5.0,>=4.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from aiohttp==3.3.2->ledfx) (4.7.6)
Requirement already satisfied: idna>=2.0 in c:\users\neil\anaconda3\envs\ledfx\lib\site-packages (from idna-ssl>=1.0->aiohttp==3.3.2->ledfx) (2.10)

(ledfx) C:\Users\Neil>ledfx --open-ui
Loading configuration file from C:\Users\Neil\AppData\Roaming\.ledfx
Started webinterface at http://192.168.0.13:8888
Traceback (most recent call last):
  File "c:\users\neil\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 142, in _audio_sample_callback
    self._invoke_callbacks()
  File "c:\users\neil\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 149, in _invoke_callbacks
    callback()
  File "c:\users\neil\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 512, in _audio_data_updated
    self.audio_data_updated(self.audio)
  File "c:\users\neil\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\pitchSpectrum(Reactive).py", line 35, in audio_data_updated
    midi_value = self.pitch_o(data.audio_sample())[0]
ValueError: can only accept vector of float as input
[2020-12-06 14:12:57] ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "c:\users\neil\anaconda3\envs\ledfx\lib\genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Neil\\anaconda3\\envs\\ledfx\\Scripts\\firebird.WSH'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\neil\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 100, in async_start
    import webbrowser
  File "c:\users\neil\anaconda3\envs\ledfx\lib\webbrowser.py", line 531, in <module>
    if shutil.which(browser):
  File "c:\users\neil\anaconda3\envs\ledfx\lib\shutil.py", line 1157, in which
    if _access_check(name, mode):
  File "c:\users\neil\anaconda3\envs\ledfx\lib\shutil.py", line 1113, in _access_check
    return (os.path.exists(fn) and os.access(fn, mode)
  File "c:\users\neil\anaconda3\envs\ledfx\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError

**Comment by Mattallmighty** [comment]
Hey @Neilo61,

Are you aware of: https://ledfx.app/ 
We have made a Windows .exe file that makes installing LedFx a breeze (available from https://ledfx.app/).

If you are using another platform, https://ledfx.readthedocs.io/en/docs/installing.html# 
Can see on your trace there are missing requirements. Can you please let me know what hardware & OS you are attempting to install this on?
Best to contact LedFx problems/bugs through our LedFx Discord community: https://discord.com/invite/wJ755dY
