### ISSUE TITLE
[windows 10] configuration lost when closing / create a shortcut to activate the env AND executing "ledfx" command

### ISSUE THREAD

**Issue by sladaar** [ahodges9/LedFx#51]
First of all, thanks a lot for this project, it's awesome!

So, i'm on windows and installed ledfx in Anaconda.
To run the visualization i needed a shortcut without entering the environment, so i found the executable in 
C:\Users\"myuser"\Anaconda3\envs\ledfx\Scripts\ledfx.exe 
and so far no problems.
BUT, when i close the window it seems i lose the configuration file, 
C:\Users\"myuser"\AppData\Roaming\.ledfx\config.yaml
or however i can't run the visualization no more because it fires me an error:

```
Loading` configuration file from C:\Users\mbibox\AppData\Roaming\.ledfx
Traceback (most recent call last):
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 553, in validate_dict
    raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mbibox\Anaconda3\envs\ledfx\Scripts\ledfx.exe\__main__.py", line 7, in <module>
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\ledfx\__main__.py", line 88, in main
    ledfx = LedFxCore(config_dir = args.config)
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 23, in __init__
    self.config = load_config(config_dir)
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\ledfx\config.py", line 87, in load_config
    return CORE_CONFIG_SCHEMA(yaml.load(file))
  File "c:\users\mbibox\anaconda3\envs\ledfx\lib\site-packages\voluptuous\schema_builder.py", line 271, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a dictionary`
```

Thanks in advance!

with further investigations it seems that executing that exe could be the problem, because running the script inside the anaconda environment could resolve the issue.
So i'm trying to create a shortcut to activate the env AND execute "ledfx" command.

**Comment by sladaar** [comment]
did it by myself!

**Comment by GrandNewbien** [comment]
@sladaar How did you manage to do this?

**Comment by Hokyjack** [comment]
Make a BAT script containing:
call activate ledfx
call c:\Users\<YOUR_USERNAME>\Anaconda3\envs\ledfx\Scripts\ledfx.exe

**Comment by tihoangyeudau** [comment]
@Hokyjack I did it but it did not work.
```
(base) C:\Users\tuant>call C:\Users\tuant\anaconda3\Scripts\activate.bat ledfx

(ledfx) C:\Users\tuant>call C:\Users\tuant\anaconda3\envs\ledfx\Scripts\ledfx.exe
Loading configuration file from C:\Users\tuant\AppData\Roaming\.ledfx
Loading default presets from C:\Users\tuant\anaconda3\envs\ledfx\Lib\site-packages\ledfx
Traceback (most recent call last):
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\tuant\anaconda3\envs\ledfx\Scripts\ledfx.exe\__main__.py", line 7, in <module>
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\__main__.py", line 89, in main
    ledfx.start(open_ui = args.open_ui)
  File "c:\users\tuant\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 66, in start
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

**Comment by Geraldidi** [comment]
don't know if this is the best way but works for me :)

call "C:\Users\admin\anaconda3\Scripts\activate.bat" ledfx & "C:\Users\admin\anaconda3\envs\ledfx\Scripts\ledfx.exe" --open-ui
