### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Zafrilla227** [ahodges9/LedFx#52]
When installing fastled on windows 10 I get this error message:

  

> ERROR: Failed building wheel for aiohttp
  Running setup.py clean for aiohttp
Failed to build aiohttp
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Zafri\Anaconda3\envs\ledfx\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Zafri\\AppData\\Local\\Temp\\pip-install-20kry1sc\\pyaudio\\setup.py'"'"'; __file__='"'"'C:\\Users\\Zafri\\AppData\\Local\\Temp\\pip-install-20kry1sc\\pyaudio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Zafri\AppData\Local\Temp\pip-wheel-dq_b4n6b' --python-tag cp37
       cwd: C:\Users\Zafri\AppData\Local\Temp\pip-install-20kry1sc\pyaudio\
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  copying src\pyaudio.py -> build\lib.win-amd64-3.7
  running build_ext
  building '_portaudio' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Zafri\AppData\Local\Temp\pip-install-20kry1sc\pyaudio\setup.py", line 122, in <module>
      extra_link_args=extra_link_args)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
      _build_ext.run(self)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
      _build_ext.build_extension(self, ext)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\command\build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\_msvccompiler.py", line 346, in compile
      self.initialize()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\distutils\_msvccompiler.py", line 239, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
      return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\site-packages\setuptools\msvc.py", line 1620, in return_env
      if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
    File "C:\Users\Zafri\Anaconda3\envs\ledfx\lib\genericpath.py", line 30, in isfile
      st = os.stat(path)
  TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
  ----------------------------------------
 

> ERROR: Failed building wheel for pyaudio
 Running setup.py clean for pyaudio
Failed to build pyaudio
ERROR: Could not build wheels for aiohttp which use PEP 517 and cannot be installed directly

Could anyone help me? Thanks in advance.

**Comment by Zafrilla227** [comment]
I managed to solve it, here's the post:
https://www.reddit.com/r/learnpython/comments/drf5k4/error_building_wheels_using_pip_install/

**Comment by d00mfish** [comment]
@Zafrilla227 how did you fix the error? I went through the reddit post but nothing did help.

**Comment by Zafrilla227** [comment]
@d00mfish I can't really tell you more than what it is at the reddit post, make sure to install and make the changes mentioned there about installing the visual c++ redistributable and upgrading the setuptools from conda. If that doesn't work, you may find help at the discord server or just open another issue. Good Luck!
