### ISSUE TITLE
AttributeError: type object 'RestEndpoint' has no attribute '_registry'

### ISSUE THREAD

**Issue by dansleboby** [ahodges9/LedFx#54]
How to fix that?

Traceback (most recent call last):
  File "/home/gpaquin/.local/bin/ledfx", line 7, in <module>
    from ledfx.__main__ import main
  File "/home/gpaquin/.local/lib/python3.5/site-packages/ledfx/__main__.py", line 26, in <module>
    from ledfx.core import LedFxCore
  File "/home/gpaquin/.local/lib/python3.5/site-packages/ledfx/core.py", line 11, in <module>
    from ledfx.http import HttpServer
  File "/home/gpaquin/.local/lib/python3.5/site-packages/ledfx/http.py", line 6, in <module>
    from ledfx.api import RestApi
  File "/home/gpaquin/.local/lib/python3.5/site-packages/ledfx/api/__init__.py", line 8, in <module>
    class RestEndpoint(BaseRegistry):
  File "/home/gpaquin/.local/lib/python3.5/site-packages/ledfx/utils.py", line 137, in no_registration
    del cls._registry[name]
AttributeError: type object 'RestEndpoint' has no attribute '_registry'

**Comment by richyxi** [comment]
Try python 3.6
