### ISSUE TITLE
voluptuous.error

### ISSUE THREAD

**Issue by ernie-t** [ahodges9/LedFx#58]
root@raspberrypi:~# ledfx
Loading configuration file from /root/.ledfx
Started webinterface at http://192.168.178.107:8888
[2019-11-21 17:41:33] ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 553, in validate_dict
    raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/ledfx/api/__init__.py", line 26, in handler
    return await method(**{arg_name: available_args[arg_name] for arg_name in wanted_args})
  File "/usr/local/lib/python3.6/site-packages/ledfx/api/device_effects.py", line 50, in put
    device.set_effect(effect)
  File "/usr/local/lib/python3.6/site-packages/ledfx/devices/__init__.py", line 49, in set_effect
    self._active_effect.activate(self.pixel_count)
  File "/usr/local/lib/python3.6/site-packages/ledfx/effects/audio.py", line 433, in activate
    self._ledfx.audio = MelbankInputSource(self._ledfx, self._ledfx.config.get('audio', {}))
  File "/usr/local/lib/python3.6/site-packages/ledfx/effects/audio.py", line 203, in __init__
    config = self.CONFIG_SCHEMA(config)
  File "/usr/local/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 271, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a dictionary

How can I fix this? Thanks for your time & support :-)

**Comment by charlieali** [comment]
delete the ledfx.yaml file wherever that's stored and retry.

**Comment by worm00111** [comment]
I have the same issue and I tried searching for ledfx.yaml but it's nowhere on my system. Btw, this is on Windows using WLED.

Perhaps you could say where to find this file?

**Comment by charlieali** [comment]
My bad, it's actually config.yaml and in on windows it is in C:\Users\user\AppData\Roaming\.ledfx , no clue where it is on linux. Deleting and allowing the app to create a new yaml on startup fixed these voluptuous errors each time for me.

**Comment by worm00111** [comment]
Nice one, it worked! Appreciate your help :)
