### ISSUE TITLE
Unable to start ledfx

### ISSUE THREAD

**Issue by theSC** [ahodges9/LedFx#60]
Raspbian Buster-lite.

Installing ledfx seems to have succeeded but upon trying to start ledfx I get the following errors:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/ledfx", line 6, in <module>
    from ledfx.__main__ import main
  File "/home/pi/.local/lib/python3.7/site-packages/ledfx/__main__.py", line 26, in <module>
    from ledfx.core import LedFxCore
  File "/home/pi/.local/lib/python3.7/site-packages/ledfx/core.py", line 11, in <module>
    from ledfx.http import HttpServer
  File "/home/pi/.local/lib/python3.7/site-packages/ledfx/http.py", line 7, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.4" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by theSC** [comment]
Anything?

**Comment by theSC** [comment]
Would still love any help someone could give me. This is a fresh install of the OS and ledfx with nothing else.  I am at a loss as to what to do

**Comment by ahodges9** [comment]
Are you trying to install on RaspberryPi? Have you tried following the instructions here? #62

**Comment by theSC** [comment]
Yes I am using a RaspberryPi. The linked instructions fail for me at conda create -n ledfx.  I get "illegal instruction"
