### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by henmel** [ahodges9/LedFx#81]
Hi,

Thanks for a great program! I had this setup and working on windows 10 for some time. The other day I started ledfx from anaconda terminal as usual and deleted all devices, as I wanted to start from scratch since the IP's have changed. LedFX crashed and when I tried to restart, I get the following error:

```
(ledfx) C:\Users\henry>ledfx --open-ui
Loading configuration file from C:\Users\henry\AppData\Roaming\.ledfx
Started webinterface at http://192.168.56.1:8888
Traceback (most recent call last):
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 142, in _audio_sample_callback
    self._invoke_callbacks()
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 149, in _invoke_callbacks
    callback()
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\audio.py", line 512, in _audio_data_updated
    self.audio_data_updated(self.audio)
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\rain(Reactive).py", line 99, in audio_data_updated
    self.pixels = self.get_drops()
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\__init__.py", line 186, in pixels
    pixels = blur_pixels(pixels=pixels, sigma=self._config['blur'])
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\effects\__init__.py", line 49, in blur_pixels
    rgb_array[0] = smooth(rgb_array[0], sigma)
ValueError: could not broadcast input array from shape (5) into shape (10)
[2020-02-26 19:18:00] ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "c:\users\henry\anaconda3\envs\ledfx\lib\genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\system32\\seamonkey.WSF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\henry\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 100, in async_start
    import webbrowser
  File "c:\users\henry\anaconda3\envs\ledfx\lib\webbrowser.py", line 531, in <module>
    if shutil.which(browser):
  File "c:\users\henry\anaconda3\envs\ledfx\lib\shutil.py", line 1157, in which
    if _access_check(name, mode):
  File "c:\users\henry\anaconda3\envs\ledfx\lib\shutil.py", line 1113, in _access_check
    return (os.path.exists(fn) and os.access(fn, mode)
  File "c:\users\henry\anaconda3\envs\ledfx\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError

```
It looks like possibly "C:\\Windows\\system32\\seamonkey.WSF" is missing. I tried restarting the computer and even tried to restore the whole env/ledfx folder, from a backup, but still get the error. Any help is greatly appreciated.

**Comment by THATDONFC** [comment]
If you want to start over, you can always remove your ledfx env and create a new one. It takes less than 5 minutes.

**Comment by henmel** [comment]
Thank you. I reset it, as you suggested and it works again.
