### ISSUE TITLE
DLL load failed while importing _portaudio

### ISSUE THREAD

**Issue by StefanRu1** [ahodges9/LedFx#86]
I am on Windows 10 and did everything as described in the guide.
I have used minconda3 and Visual Studio Build Tools 2019.
Everything is installed but when loading ledfx i get this error:

`(ledfx) C:\Users\Stefan>ledfx --open-ui
Loading configuration file from C:\Users\Stefan\AppData\Roaming\.ledfx
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "c:\users\stefan\.conda\envs\ledfx\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\stefan\.conda\envs\ledfx\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stefan\.conda\envs\ledfx\Scripts\ledfx.exe\__main__.py", line 7, in <module>
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\__main__.py", line 88, in main
    ledfx = LedFxCore(config_dir = args.config)
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\core.py", line 36, in __init__
    self.http = HttpServer(
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\http.py", line 19, in __init__
    self.api = RestApi(ledfx)
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\api\__init__.py", line 33, in __init__
    super().__init__(ledfx, RestEndpoint, self.PACKAGE_NAME)
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\utils.py", line 189, in __init__
    self.import_registry(package)
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\utils.py", line 225, in import_registry
    importlib.import_module(name)
  File "c:\users\stefan\.conda\envs\ledfx\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\ledfx\api\audio_devices.py", line 6, in <module>
    import pyaudio
  File "c:\users\stefan\.conda\envs\ledfx\lib\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: DLL load failed while importing _portaudio: Das angegebene Modul wurde nicht gefunden.

(ledfx) C:\Users\Stefan>`

I tried a few things to get portaudio running but nothing i found on the web worked.
Error stays the same. 

Can someone help me?

Best regards,
Stefan

**Comment by StefanRu1** [comment]
Ok, i solved it by getting the pyaudio whl file.
Deleting all from anaconda what was there with pyadio und install it with help of the whl file new.
After this it worked fine.

Is there a way to make the installation process easier?

Thanks a lot for the cool software. The effects are incredible.

Thanks,
Stefan

**Comment by northerntaco** [comment]
> Ok, i solved it by getting the pyaudio whl file.
> Deleting all from anaconda what was there with pyadio und install it with help of the whl file new.
> After this it worked fine.
> 
> Is there a way to make the installation process easier?
> 
> Thanks a lot for the cool software. The effects are incredible.
> 
> Thanks,
> Stefan

I got the same error as you. Could you explain the steps you took to resolve?
