### ISSUE TITLE
ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved

### ISSUE THREAD

**Issue by jpunsal** [ahodges9/LedFx#93]
Hi,

Last month I had everything working great. I went to boot it up today and kept getting the following error:

`(ledfx) C:\Users\admin>ledfx --open-ui
Loading configuration file from C:\Users\admin\AppData\Roaming\.ledfx
Started webinterface at http://192.168.1.216:8888
[2020-04-06 19:29:09] ERROR:ledfx.core:Exception in core event loop: Task exception was never retrieved
Traceback (most recent call last):
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\core.py", line 97, in async_start
    self.devices.create_from_config(self.config['devices'])
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 182, in create_from_config
    self._ledfx.devices.get_device(device['id']).set_effect(effect)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 52, in set_effect
    self.activate()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\udp.py", line 23, in activate
    super().activate()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 126, in activate
    self.thread_function()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 91, in thread_function
    self.process_active_effect()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 77, in process_active_effect
    self.flush(assembled_frame)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\udp.py", line 55, in flush
    self._sock.sendto(bytes(udpData), (self._config['ip_address'], self._config['port']))
socket.gaierror: [Errno 11001] getaddrinfo failed
[2020-04-06 19:29:09] ERROR:ledfx.core:Exception in core event loop: Exception in callback Device.thread_function()
Traceback (most recent call last):
  File "c:\anaconda3\envs\ledfx\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 91, in thread_function
    self.process_active_effect()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 77, in process_active_effect
    self.flush(assembled_frame)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\udp.py", line 55, in flush
    self._sock.sendto(bytes(udpData), (self._config['ip_address'], self._config['port']))
socket.gaierror: [Errno 11001] getaddrinfo failed
[2020-04-06 19:29:09] ERROR:ledfx.core:Exception in core event loop: Exception in callback Device.thread_function()
Traceback (most recent call last):
  File "c:\anaconda3\envs\ledfx\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 91, in thread_function
    self.process_active_effect()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 77, in process_active_effect
    self.flush(assembled_frame)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\udp.py", line 55, in flush
    self._sock.sendto(bytes(udpData), (self._config['ip_address'], self._config['port']))`

Then it just repeats:
`socket.gaierror: [Errno 11001] getaddrinfo failed
[2020-04-06 19:29:09] ERROR:ledfx.core:Exception in core event loop: Exception in callback Device.thread_function()
Traceback (most recent call last):
  File "c:\anaconda3\envs\ledfx\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 91, in thread_function
    self.process_active_effect()
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\__init__.py", line 77, in process_active_effect
    self.flush(assembled_frame)
  File "c:\anaconda3\envs\ledfx\lib\site-packages\ledfx\devices\udp.py", line 55, in flush
    self._sock.sendto(bytes(udpData), (self._config['ip_address'], self._config['port']))
socket.gaierror: [Errno 11001] getaddrinfo failed`

I tried to remove the environment from Anaconda then start from scratch since it seems similar to [this issue](https://github.com/ahodges9/LedFx/issues/81) but got the same result.
What is really wired is that it was working and I can't think of anything that I changed.

Any help would be much appreciated!

Thanks!

**Comment by jpunsal** [comment]
Here's some troubleshooting I just went through.

Uninstall Anaconda.

- Download 64-bit 3.7 version graphical installer from Anaconda from [here.](https://www.anaconda.com/distribution/#download-section)
- Run the installer as admin and install to C:\anaconda3 with default settings.
- Run Anaconda Navigator (anaconda3) from the start menu as admin.
- Open Anaconda3 terminal and type "conda create --name ledfx python=3.6" and type "y" to proceed.
- Type "conda activate ledfx". [Here's the result of that.](https://pastebin.com/uCYEMDY9)
- Type "conda activate ledfx". The prompt now says "(ledfx) C:\Users\admin>" so I think it's active.
- Type "conda config --add channels conda-forge". It then returns "Warning: 'conda-forge' already in 'channels' list, moving to the top". I'm not sure what this means.
- Type "conda install aubio portaudio pywin32" then type "y" to proceed. [This is the result.](https://pastebin.com/hbAg8p6P)
- Type "pip install ledfx". [Here's the result.](https://pastebin.com/5j6sKmt5)
- Type "ledfx --open-ui". [It then gives me the same error as above.](https://pastebin.com/UjwmAe90)

I know I've also had problems with anaconda recognizing pyaudio in the past. The work around I figured out was to use "pip install PyAudio". 

If anyone wants any more information please let me know.

**Comment by jpunsal** [comment]
I removed windows and installed linux. I'm getting another error now but won't be working on this in windows anymore so I'm closing the issue.
